name: simply_responsive

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze project source
        run: flutter analyze lib test
      - name: Run tests, process code coverage
        run: | 
          flutter test --coverage
          lcov --list coverage/lcov.info
          genhtml coverage/lcov.info --output coverage/
      - name: Archive Code Coverage
        uses: actions/upload-artifact@v2
        with: 
          name: code-coverage
          path: coverage/
